PREFIX ex: <http://example.org/>

SELECT ?genero (COUNT(?libro) AS ?numLibros) (SUM(?paginas) AS ?totalPaginas) (AVG(?paginas) AS ?mediaPaginas)
WHERE {
    ?libro a ex:Libro ;
           ex:genero ?genero ;
           ex:paginas ?paginas .
}
GROUP BY ?genero
HAVING(COUNT(?libro) > 1)