PREFIX ex: <http://example.org/>

SELECT ?nombre ?email ?nombreCiudad
WHERE {
    GRAPH ex:perfiles {
        ?persona ex:email ?email .
    }
    GRAPH ex:personas {
        ?persona ex:nombre ?nombre ;
                 ex:viveEn ?ciudad .
        ?ciudad ex:nombre ?nombreCiudad .
    }
}